---
- name: My first playbook (Name)
  hosts: all

  tasks:
    # My first comment
    - name: Hello World! 1
      win_shell: echo "Hi! The playbook ran! 1”
      
    # My second comment  
    - name: Hello World! 2 
      win_shell: echo "Hi! The playbook ran! 2”
