---
- name: My first playbook (Name)
  hosts: all

  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  tasks:
    # My first comment
    - name: "Hello World! 1"
      shell: echo "{{ my_variable }}"
      
    # My second comment  
    - name: "Hello World! 2"
      shell: echo "Hi! The playbook ran! 2"
     
    #Create an empty file
    - name: Creating an empty file
      file:
        path: "/tmp/MyFile.txt"
        state: touch
