---
- name: Third playbook
  hosts: all
  gather_facts: no

  tasks:
    # My first comment
    - name: Create file
      copy:
        content: "This is my content"
        dest: /test.txt
      delegate_to: localhost
      
    - name: capture output of whoami command
      win_shell: whoami
      register: who_am_i

    - name: Write debug message
      debug:
        msg: “{{ who_am_i }}”


