---
- hosts: all
  gather_facts: yes

  tasks:

  # Read contents of file
  - name: Read contents of file
    win_shell: Get-Content -Path c:\Windows\System32\Drivers\etc\hosts 
    register: hosts_info
    when: ansible_system == "Win32NT" 

  - name: Add line to file if
    win_lineinfile:
      path: c:\Windows\System32\Drivers\etc\hosts
      line: \n192.168.1.99 foo.lab.net foo
      insertafter: EOF
    when: ansible_system == "Win32NT" and not '\n192.168.1.99 foo.lab.net foo' in hosts_info.stdout 
