---
- name: My first playbook (Name)
  hosts: all

  vars:
    key_file: "My variable in the playbook"

  vars_files:
    - ./variables.yml

  tasks:
    # My first comment
    - name: "Hello World! 1"
      shell: echo "{{ my_variable }}"
      
    # My second comment  
    - name: "Hello World! 2"
      shell: echo "Hi! The playbook ran! 2"
